FROM python:3-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update && apk add \
    postgresql-dev gcc python3-dev musl-dev \
    zlib-dev jpeg-dev libpq libffi-dev

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache -r requirements.txt

COPY . .
