FROM python:3-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update && apk add \
    postgresql-dev gcc python3-dev musl-dev \
    zlib-dev libjpeg-turbo-dev libpq

RUN mkdir -p /usr/app

WORKDIR /usr/src/app

COPY ./requirements.txt .

RUN pip install --upgrade pip
RUN pip wheel --no-cache-dir --wheel-dir ./wheels -r requirements.txt
RUN pip install --no-cache ./wheels/*

COPY . .
