# Generated by Django 3.1.4 on 2020-12-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
