# Generated by Django 3.1.4 on 2020-12-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201227_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Client status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_sitter',
            field=models.BooleanField(default=False, verbose_name='Sitter status'),
        ),
    ]
