# Generated by Django 3.1.4 on 2020-12-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201228_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, help_text='Designates that this user is a Client.', verbose_name='Client status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_sitter',
            field=models.BooleanField(default=False, help_text='Designates that this user is a Sitter.', verbose_name='Sitter status'),
        ),
    ]
