# Generated by Django 3.1 on 2021-01-02 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201229_0031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientMore',
        ),
        migrations.RenameModel(
            old_name='Sitter',
            new_name='SitterMore',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
