# Generated by Django 3.1.4 on 2020-12-24 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='Time and date of creation')),
                ('offer_datetime', models.DateTimeField(help_text='Time and date when sitter is needed')),
                ('client_address', models.CharField(help_text='Client address', max_length=255)),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(0, 'Cash'), (1, 'Card')], default=0, help_text='Payment method')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (0, 'Declined')], default=1, help_text='Status of the offer')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_offer_sent', related_query_name='offers_offers', to=settings.AUTH_USER_MODEL)),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_offer_recv', related_query_name='offers_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
