# Generated by Django 3.1.4 on 2020-12-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='comment',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
