# Generated by Django 3.1.4 on 2020-12-22 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0002_auto_20201221_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Time and date of creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Declined')], default=0, help_text='Status of the offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_offer_sent', related_query_name='offers_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cash'), (1, 'Card')], default=0, help_text='Payment method'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_offer_recv', related_query_name='offers_offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
