# Generated by Django 3.1.4 on 2020-12-24 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20201224_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review about Client', 'verbose_name_plural': 'Reviews about Clients'},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name': 'Review about Sitter', 'verbose_name_plural': 'Reviews about Sitters'},
        ),
    ]
